# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train_line', models.CharField(max_length=20)),
                ('train_num', models.CharField(max_length=20)),
                ('effective_date', models.DateTimeField()),
            ],
        ),
    ]
