# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directtrains', '0002_auto_20160830_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directtrain',
            name='effective_date',
            field=models.DateField(),
        ),
    ]
