# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directtrains', '0003_auto_20160830_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
